export {
  ErrorCode,
  AuthErrorCodes,
  ValidationErrorCodes,
  ResourceErrorCodes,
  BusinessErrorCodes,
  ExternalErrorCodes,
  SystemErrorCodes,
  ErrorCodeHttpStatus,
  isAuthError,
  isValidationError,
  isResourceError,
  isBusinessError,
  isExternalError,
  isSystemError,
  isClientError,
  isServerError,
  type ErrorCodeType,
} from "./error-codes";

export {
  DefaultUserMessages,
  getUserMessage,
  GENERIC_ERROR_MESSAGE,
  UNKNOWN_ERROR_MESSAGE,
} from "./user-messages";

export {
  AppError,
  isAppError,
  isAppErrorLike,
  type ErrorDetails,
  type ErrorMetadata,
  type ValidationFieldError,
} from "./app-error";

export {
  createError,
  notFound,
  alreadyExists,
  validationError,
  unauthorized,
  forbidden,
  insufficientPermissions,
  businessRule,
  operationNotAllowed,
  invalidStateTransition,
  internal,
  fromUnknown,
  fromDatabaseError,
  fileError,
  serviceUnavailable,
  timeout,
  rateLimited,
  isDevelopment,
  type ErrorOptions,
  createNotFoundError,
  createAlreadyExistsError,
  createResourceError,
  createValidationError,
  createRequiredFieldError,
  createInvalidDateRangeError,
  createDuplicateEntryError,
  createUnauthorizedError,
  createForbiddenError,
  createInsufficientPermissionsError,
  createInvalidCredentialsError,
  createSessionExpiredError,
  createBusinessRuleError,
  createOperationNotAllowedError,
  createInvalidStateTransitionError,
  createServiceUnavailableError,
  createSharePointError,
  createDatabaseError,
  createInternalError,
  createUnexpectedError,
  throwNotFoundError,
  throwValidationError,
  throwUnauthorizedError,
  throwForbiddenError,
  throwInternalError,
  throwConflictError,
} from "./error-factory";

export {
  transformToTRPCError,
  appErrorToTRPCError,
  zodErrorToAppError,
  formatErrorForClient,
  handleDatabaseOperation,
  type TRPCErrorCause,
} from "./trpc-handler";

export {
  parseApiError,
  getFieldErrors,
  getFieldError,
  hasValidationErrors,
  isValidationErrorResponse,
  isAuthErrorResponse,
  requiresReauthentication,
  isNotFoundError,
  isServerError as isServerErrorResponse,
  getErrorTitle,
  formatSupportMessage,
  createMutationErrorHandler,
  type ClientValidationError,
  type ParsedApiError,
  type MutationErrorHandlerOptions,
} from "./client-utils";
